# Mar 14, 2019
## Variables
2018020143 민정원

## 1. class 'dict'
   : **사전 형식**의 리스트 만들기  
  

### 예제1.  
리스트 a = {'John' : 'teacher', 'Emma' : 'doctor', 'Peter' : 'cook', 'Jane' : 'pianist'}     
**리스트 a**의 **유형**을 **보여라**.


In [7]:
a = {'John' : 'teacher', 'Emma' : 'doctor', 'Peter' : 'cook', 'Jane' : 'pianist'}
print(type(a))

<class 'dict'>


### 예제2.  
리스트 a = {'John' : 'teacher', 'Emma' : 'doctor', 'Peter' : 'cook', 'Jane' : 'pianist'}  
**리스트 a**의 **Emma에 대응하는 항목**을 **보여라**.


In [8]:
print(a['Emma'])

doctor


### 예제3.  리스트 안의 리스트
리스트 b = { 1 : 'music', 2 : 'science', 3 : ['English', 'Chinese', 'Korean']}  
**리스트 a**의 **3에 대응하는 항목**을 **보여라**.

In [11]:
b = { 1 : 'music', 2 : 'science', 3 : ['English', 'Chinese', 'Korean']}  
print(b[3])

['English', 'Chinese', 'Korean']


## 2. numpy 사용하기  - array, matrix
* python을 설치하지 않고 anaconda를 설치한 이유  
: anaconda를 설치하면 자동으로 python에서 사용 가능한 여러 package가 설치되어 필요한 package를 일일이 다운받지 않아도 됨.  
* import : anaconda를 설치하여 하드디스크에 다운받아진 package를 메모리로 불러들이기. 
* 어떤 한 package 내에는 여러 함수가 저장되어 있기 때문에 불러들인 이후 사용 가능.

### 예제1.  
**numpy**라는 라이브러리를 **'np'라는 이름으로** memory로 **불러들이자.** 

In [12]:
import numpy as np

### 예제2.  numpy 라이브러리 내의 array 함수 사용하기
* 리스트 c = [(2, 3, 5), (7, 11, 13)]
* 리스트 c에 **numpy 라이브러리 내의 array함수**를 적용시킨 것을 C라 하자.
* C의 **유형을 보여라.**

In [14]:
c = [(2, 3, 5), (7, 11, 13)]
C = np.array(c)      
print(C)           # array : 리스트를 행렬 '모양'으로 바꿔주는 함수(행렬로 바꿔주지는 않음) 
print(type(C))    

[[ 2  3  5]
 [ 7 11 13]]
<class 'numpy.ndarray'>


### 예제3.  numpy 라이브러리 내의 array 함수 사용하기
* c = [(2, 3, 5), (7, 11, 13)]
* C = np.array(c)
* **C곱하기C**를 **보여라**.

In [28]:
c = [(2, 3, 5), (7, 11, 13)];
C = np.array(c);
print(C*C)                    # 행렬의 곱으로 만들어지지 않고, 결과는 단순 곱셈 형식으로 나타남. array는 리스트를 행렬 '모양'으로 만들어주는 함수이지, '행렬'로 만들어주지 않기 때문.

[[  4   9  25]
 [ 49 121 169]]


### 예제4.  numpy 라이브러리 내의 matrix 함수 사용하기
* 리스트 c = [(2, 3, 5), (7, 11, 13)]
* 리스트 c에 **numpy 라이브러리 내의 matrix함수**를 적용시킨 것을 D라 하자.
* D를 **보여라.**  
* D의 **유형을 보여라.**

In [17]:
D = np.matrix(c)
print(D)
print(type(D))

[[ 2  3  5]
 [ 7 11 13]]
<class 'numpy.matrixlib.defmatrix.matrix'>


### 예제5.  numpy 라이브러리 내의 matrix 함수 사용하기  
* D = np.matrix(c)    
* **행렬 D와 D를 곱한 것**을 **보여라**.  

In [26]:
print(D*D)    # D는 (2X3)행렬. (2X3) 행렬끼리는 곱할 수 없음.

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### 예제6.  numpy 라이브러리 내의 matrix 함수 사용하기
* (matrix).T : (matrix)를 transpose한 것.  
* D = np.matrix(c)    
* **D.T**를 **보여라**.
* **행렬 D와 D.T를 곱한 것**을 **보여라**.

In [25]:
print(D.T);     # 행렬 D를 transpose하면 (3X2)행렬이 됨.
print(D*D.T)    # (2X3)행렬 * (3X2)행렬  ->    (2X2)행렬

[[ 2  7]
 [ 3 11]
 [ 5 13]]
[[ 38 112]
 [112 339]]
